# Generated by Django 4.2.9 on 2025-05-13 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_type', models.CharField(choices=[('nutrition', 'Nutrition'), ('activity', 'Physical Activity'), ('sleep', 'Sleep'), ('hydration', 'Hydration'), ('vitals', 'Vital Signs'), ('medication', 'Medication'), ('mental', 'Mental Wellbeing'), ('general', 'General Health')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High')], default=2)),
                ('based_on', models.JSONField(help_text='Data points used to generate this recommendation')),
                ('is_read', models.BooleanField(default=False)),
                ('is_dismissed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-priority', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('trend', 'Trend Insight'), ('correlation', 'Correlation Insight'), ('progress', 'Progress Insight'), ('anomaly', 'Anomaly Detection'), ('milestone', 'Milestone Achieved')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('data_points', models.JSONField(help_text='Data used to generate this insight')),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HealthScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('nutrition_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('activity_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sleep_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('hydration_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('vitals_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('weight_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('mood_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('calculation_date', models.DateField()),
                ('calculation_details', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_scores', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-calculation_date'],
                'unique_together': {('user', 'calculation_date')},
            },
        ),
    ]
